os: Visual Studio 2015

branches:
  only:
  - master

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\appveyor\\run_with_env.cmd"
    PYTHONUNBUFFERED: 1
    BINSTAR_TOKEN:
      secure: SZHgfJd7yeEspBHogEx78Bb9rrQ5atuIalqY8J/V/uGeBNOi6yGYWtFsnI6/0dPx


  matrix:
    - PYTHON: "C:\\Miniconda"
      CONDA_PY: "27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Miniconda-x64"
      CONDA_PY: "27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      CONDA_PY: "36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - set PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - conda update -yq --all
  - conda install -yq conda-build jinja2 anaconda-client
  - conda config --add channels omnia
  - conda config --add channels conda-forge
  - powershell .\\devtools\\appveyor\\missing-headers.ps1
  # conda-build for some inane reason, effectively puts C:\cygwin\bin at the
  # front of the PATH, ahead of everything else, regardless. See
  # https://github.com/conda/conda-build/blob/master/conda_build/external.py#L19
  # On Appveyor, the version of git installed there doesn't work
  # outside of the cygwin envronment, so despite a perfectly good version of
  # git being installed somewhere else (git for windows, which works properly),
  # conda-build will always choose to use the broken one. The only way I could
  # think of to fix this is just to delete the broken one, so that it never gets
  # found by conda-build. Or someone could fix conda-build.
  - "del C:\\cygwin\\bin\\git.exe"

build: false

test_script:
  - ps: if (($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null) -and ($env:APPVEYOR_REPO_BRANCH -eq "master")) { $env:UPLOAD = "--upload omnia" } else { $env:UPLOAD = " " }
  - "%CMD_IN_ENV% python conda-build-all %UPLOAD% --python %CONDA_PY% *"
